name: Android APK (assembleDebug, force-stable)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK pieces
        uses: android-actions/setup-android@v3

      - name: Install platforms/build-tools & accept licenses
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Gradle wrapper -> 8.7 (before build)
        working-directory: android
        run: |
          chmod +x ./gradlew || true
          ./gradlew wrapper --gradle-version 8.7 --distribution-type all
          cat ./gradle/wrapper/gradle-wrapper.properties

      - name: Show Gradle/AGP versions
        working-directory: android
        run: |
          ./gradlew -v || true
          grep -R --line-number "com.android.tools.build:gradle" . || true

      - name: Assemble debug APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon --stacktrace --warning-mode all clean assembleDebug

      - name: Upload APK (debug)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            android/**/build/*.log
            android/**/build/reports/**
            android/**/outputs/logs/**
            android/**/build/outputs/**
