name: Android APK (assembleDebug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ 자바 11 (구형 Gradle/AGP 호환). 
      # 만약 로그에 "JDK 17 필요"가 뜨면 17로 바꿔 다시 시도.
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK (API 33 & 34)
        uses: android-actions/setup-android@v3
        with:
          # 두 버전 모두 설치해 빌드 스크립트와 불일치 문제 회피
          api-level: 34
          build-tools: 34.0.0
      - name: Install extra build-tools 33
        run: |
          sdkmanager "platforms;android-33" "build-tools;33.0.2"
          yes | sdkmanager --licenses

      - name: Gradle Build (assembleDebug)
        working-directory: android
        run: |
          chmod +x ./gradlew
          # 메모리 부족/캐시 이슈 회피 플래그 포함
          ./gradlew --no-daemon --stacktrace --warning-mode all clean assembleDebug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
