name: Android APK (assembleDebug, stable)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use JDK 17 (AGP 8.x 권장). 실패 시 아래 주석의 JDK 11로 바꿔 재시도 가능.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK (cmdline)
        uses: android-actions/setup-android@v3

      - name: Install platforms/build-tools & accept licenses
        shell: bash
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Show env & Gradle/AGP versions
        working-directory: android
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          ./gradlew -v || true
          grep -R --line-number "com.android.tools.build:gradle" . || true

      - name: Gradle assembleDebug
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon --stacktrace --warning-mode all clean assembleDebug

      - name: Upload APK (debug)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      # 실패시 로그도 남겨서 원인 추적 쉽게
      - name: Upload Gradle logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            android/**/build/*.log
            android/**/build/reports/**
            android/**/outputs/logs/**
            android/**/build/outputs/**
